fullnameOverride: "hyunjun-mariadb"
image:
  registry: docker.io
  repository: bitnamilegacy/mariadb
  tag: 12.0.2-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

architecture: standalone
auth:
  rootPassword: "root-mariadb"
  database: testdb
  username: "testuser"
  password: "hyunjun-mariadb"
  replicationUser: replicator
  replicationPassword: ""
  existingSecret: ""
  forcePassword: false
  usePasswordFiles: true
  customPasswordFiles: {}

initdbScripts:
  create-tables.sql: |
    USE testdb;
    
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(255) UNIQUE NOT NULL,
      password VARCHAR(255) NOT NULL,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6)
    );
    
    CREATE TABLE IF NOT EXISTS messages (
      id INT AUTO_INCREMENT PRIMARY KEY,
      message TEXT,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
      user_id VARCHAR(255)
    );

tls:
  enabled: true
  autoGenerated:
    enabled: true
    engine: helm


primary:
  name: primary
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: 12.0.2-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      metrics: 9104
    nodePorts:
      mysql: "30306"