# charts/kafka/values.yaml
global:
  storageClass: ""

fullnameOverride: "local-kafka"

image:
  registry: docker.io
  repository: bitnamilegacy/kafka # bitnami/kafka is no-longer valid
  tag: 4.0.0-debian-12-r10
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

# 명시적 리스너 프로토콜 설정 (필수)
listeners:
  client:
    protocol: SASL_PLAINTEXT
  controller:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT

# SASL 설정 - 올바른 구조 사용
sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  client:
    users:
      - user1
    passwords: "hyunjun-kafka"  # 빈 문자열 절대 사용 금지
  interbroker:
    user: inter_broker_user
    password: ""
  controller:
    user: controller_user
    password: ""
  # existingSecret 사용하지 않음 (템플릿 버그 회피)

# KRaft 모드 활성화 (Zookeeper 대신)
kraft:
  enabled: true

replicaCount: 3  # 로컬 환경에 적합

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

# Zookeeper 비활성화 (KRaft 사용)
zookeeper:
  enabled: false

resources:
  requests:
    memory: "384Mi"
    cpu: "300m"
  limits:
    memory: "768Mi"
    cpu: "600m"

service:
  type: ClusterIP
  port: 9092

externalAccess:
  enabled: false

deleteTopicEnable: true
autoCreateTopicsEnable: true

metrics:
  kafka:
    enabled: true
    serviceMonitor:
      enabled: false

securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true